/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-AUTH-RESP"
 * 	found in "../asn1/SUPL_AUTH_RESP.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_KeyIdentity3_H_
#define	_KeyIdentity3_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* KeyIdentity3 */
typedef BIT_STRING_t	 KeyIdentity3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyIdentity3;
asn_struct_free_f KeyIdentity3_free;
asn_struct_print_f KeyIdentity3_print;
asn_constr_check_f KeyIdentity3_constraint;
ber_type_decoder_f KeyIdentity3_decode_ber;
der_type_encoder_f KeyIdentity3_encode_der;
xer_type_decoder_f KeyIdentity3_decode_xer;
xer_type_encoder_f KeyIdentity3_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyIdentity3_H_ */
#include "asn_internal.h"
